mongodb/devcenter

- .github/dependabot.yml
Dependabot encountered an auth error (https://github.com/mongodb/devcenter/network/updates/271285672). There is an option to use `username` and `password` rather than just a token, so I'm trying that instead.
> Auth with username and password, not token.

- src/components/article-body/body-components/callout.tsx
- src/components/article-body/component-factory.tsx
- src/components/article-body/table-of-contents.tsx
- src/pages/[...slug].tsx
[Jira Ticket](https://jira.mongodb.org/browse/DEVHUB-1048)
Callout component (maps to blockquote). There are variants for `generic`, `note`, and `important` in the designs, and all current blockquotes will be the `generic` version. Not sure how people will choose between these variants, but I built out support for them anyway. The icons in the designs are not all available in flora, so I put a placeholder in there and will add those to flora.
I also aligned the table of contents to the image on the articles and made it sticky.
> [DEVHUB-1048] Callout component and sticky Table of Contents

- src/api-requests/get-authors.ts
- src/components/author-lockup/types.ts
- src/components/card/card.tsx
- src/components/card/types.ts
- src/interfaces/author.ts
- src/interfaces/content-item.ts
- src/mockdata/get-l1-content.ts
- src/pages/[...slug].tsx
- src/pages/index.tsx
- src/service/get-all-authors.ts
- src/service/get-all-content.ts
- src/utils/parse-authors-to-author-lockup.ts
This PR addresses two things:
1. Replace Mock authors with real authors
2. Added Graphql call to get all data needed for authors page
https://devcenter-itjrhvjc2-harikakotipalli.vercel.app/product/mongodb/enterprise-operator-kubernetes-openshift
> Authors API call- for Author type pages

- config/redirects.json
- src/pages/_middleware.ts
- tsconfig.json
Redirect to search page when a search is made from the consistent navigation.
Example: /learn/?content=Articles&text=test
will redirect to:
/search/?s=test
https://devcenter-e4ejjalz2-harikakotipalli.vercel.app/developer/learn/?content=Articles&text=test
> [DEVHUB-1216] Add redirect for search page from consistent nav

- environments/prod.yaml
Noticed that memory usage spiked to ~%50 based on the graph in https://grafana.corp.mongodb.com/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=devrel&var-workload=devcenter-frontend-web-app&var-type=Deployment. This should bring any potential spike to < 20%.
CPU usage was low and normal, but a bit high for the workload considering that we are only testing. I will be increasing this to 2 as a precaution. We can reevaluate the usage post-launch, when we have real traffic.
> Increase CPU and memory limit for prod resources

- .drone.yml
The branch declaration isn't necessary for the pipeline itself, but configured at the cron level.
Branch can declared in the cron definition on the drone cli:
`drone cron add "mongodb/devcenter" "rebuild-devcenter-prod-cron" @hourly --branch "production"`
> Remove trigger interfering with cron in Drone pipeline

- .gitignore
- next.config.js
- package.json
- src/components/author-lockup/author-image.tsx
- src/components/card/styles.ts
- src/scripts/build-rss-feed.js
- yarn.lock
Jira Ticket:
[DEVHUB-1250](https://jira.mongodb.org/browse/DEVHUB-1250)
Main thing is the RSS Feed. I originally had it running on `getStaticProps` of the homepage, but according to Next: 
> Only assets that are in the public directory at [build time](https://nextjs.org/docs/api-reference/cli#build) will be served by Next.js. Files added at runtime won't be available. We recommend using a third party service like [AWS S3](https://aws.amazon.com/s3/) for persistent file storage.
The issue with doing it outside of the context of the app is that I couldn't it to play well with using modules in the app (like `getAllContentItems`). So I decided to just pull from the search Realm function since it should be the same and only requires a single API request. I put it in the webpack config of the …
> RSS Feed, author lockup image and card background.

- package.json
- yarn.lock
1. The Web Team will begin taking web pages on .com live at 8am EDT on 6/7
2. When the pages that are featured in the latest nav release are live, we will notify everyone in the [#web-navigation](https://mongodb.slack.com/archives/C02BMJU3K36), giving the green light to launch the Consistent Nav across all websites
> [DEVHUB-1293] Consistent Nav for  MongoDB World

- src/components/seconardynavnew/dropdown-menu.tsx
Per devhub-1169, the font weight of Secondary nav: Section headers is changed to medium (500).
> Change DropDownMenuList fontWeight to medium (500)

- src/utils/product-to-logo.ts
Seems like we need "Realm (Mobile)" for the homepage. I missed this and am creating this PR as a correction.
> Add same product to logo as Realm

- src/pages/api/createFeedback.ts
- src/pages/api/requestContent.ts
- src/pages/api/updateFeedback.ts
- src/utils/logger.ts
I mainly want to be able to see if Kanopy passes a header with the client IP address. We don't have to log these headers after I find that out, but it might be nice to have that functionality just in case.
> Add headers to request logs

- src/components/showcase-card/showcase-card.tsx
Adds `variant` to `<TypographyScale />` component for correct font-size.
[DEVHUB-1180](https://jira.mongodb.org/browse/DEVHUB-1180)
> DEVHUB-1180: Homepage: Desktop - product card description text incorrect size

- src/components/seconardynavnew/mobile-styles.ts
- src/components/seconardynavnew/mobile.tsx
Ticket: https://jira.mongodb.org/browse/DEVHUB-1220
Scope:
- Sibling elements with separate bottom borders was creating a small gap in the border in mobile browsers. I moved the border up to the wrapping parent element and used `border-image` instead to achieve the active color/default border split.
- Added `strokeWeight="large"` to closed chevron in mobile view after Mike pointed it out to match open chevron's `strokeWeight`
Screenshot from current PROD:
Screenshot with `border-image` change:
> DEVHUB-1220: Secondary Nav: Mobile: Gap in nav border

- playwright-tests/pages/index.spec.ts
- playwright-tests/pages/news.spec.ts
- playwright-tests/utils.ts
- src/components/card-section/card-section.tsx
- src/page-templates/content-type/content-type.tsx
- src/page-templates/content-type/utils.ts
- src/page-templates/topic-content-type-page/topic-content-type-page-template.tsx
- src/pages/_app.tsx
- src/pages/news.tsx
Added an aggregated news & announcement page to `/news` route:
- Hid "Request an X" button for news & announcements
- Pluralized couple content type to fix the extra "s" at the end  
- Added "All News & Announcements" link
- Incorporated a simple PlayWright Test
To access the page, please click All News & Announcements link on News & Announcement of a particular product. For example, land on `/products/atlas/news/` and click All News & Announcement.
> [DEVHUB-1256] Added Aggregated News & Announcement Page

- src/page-templates/main-content-page/content-page-template.tsx
- src/page-templates/main-content-page/util.ts
Rating feature was already available to some content types such as articles. This change enables other content types to also offer the rating feature.
Per Rachelle's comment in [Ticket 1350](https://jira.mongodb.org/browse/DEVHUB-1350), it is "Rate this announcement" for news & announcements category.
> [DEVHUB-1350] Enable rating feature for other content types

- .drone.yml
The step was trying to clone the branch of the build that was just merged, but since the branch was deleted, it wasn't able to do the clone. This disables the clone step.
> Adjust preview to actually delete the deployment

- .drone.yml
- README.md
- environments/staging.yaml
Updates based on advisory.
Will need to create a KANOPY ticket for them to correct the /developer path configuration.
> Remove CDN ingress, replace .staging with new CDN hostname

- package.json
- src/components/showcase-card/showcase-card.tsx
- yarn.lock
Per Angelo's suggestion, I went through all uses of the Flora Link component and made any changes to account for the breaking change they introduced in v0.22.5. They reverted the change in their most recent release (0.22.6), so it doesn't affect anything in this PR, but we will be ready when they reimplement that change.
> [CHORE] Upgrade flora, account for link styling

- src/components/card/styles.ts
The long URLs in the video descriptions were causing some weird overflow behavior.
> [hotfix] Add line break to card descriptions.

- src/scripts/build-rss-feed.js
Often, when `yarn build` and tests are run, the build RSS feed script fails on the following error "AxiosError: maxContentLength size of Infinity exceeded" (examples: https://github.com/mongodb/devcenter/runs/7726957248?check_suite_focus=true, https://github.com/mongodb/devcenter/runs/7581091449?check_suite_focus=true, )
```
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the …
```
> Fix ERR_UNHANDLED_REJECTION

- src/utils/product-to-logo.ts
[DEVHUB-1395](https://jira.mongodb.org/browse/DEVHUB-1395)
The actual updates to these tutorials will take place in strapi, but we do need this icon before we start that.
> [DEVHUB-1395] Add Data Federation product logo

- src/components/seconardynavnew/desktop.tsx
[[DEVHUB-1168] Secondary nav links are spaced incorrectly (desktop large)](https://jira.mongodb.org/browse/DEVHUB-1168)
On desktop large view, the spacing between links in the SecondaryNav was too large. Reduced from `inc90` to `inc60`
> [DEVHUB-1168] SecondaryNav link spacing fix

- src/components/breadcrumbs/breadcrumbs.tsx
- src/components/card/styles.ts
[[DEVHUB-1234] Text too bold in Safari](https://jira.mongodb.org/browse/DEVHUB-1234)
The text in safari for breadcrumbs/pills was bold compared to the same text on Chrome:
Explicitly setting a font weight seems to fix this issue:
> [DEVHUB-1234] Fix Breadcrumb/Pill boldness issue in Safari

- src/components/series-card/series-card.test.tsx
- src/components/series-card/series-card.tsx
- src/components/series-card/types.ts
- src/page-templates/main-content-page/content-page-template.tsx
Just noticed we were including the current article in the article series card. Also fixed the safari mono boldness issue here.
https://www.mongodb.com/developer/products/realm/realm-data-types/
**Before:**
**After:**
> [FIX] Don't include current article in "more in this series"

- src/components/article-body/table-of-contents.tsx
- src/components/hero/utils.tsx
- src/components/tag-section/tag-section.test.tsx
- src/components/tag-section/tag-section.tsx
- src/components/tag-section/types.ts
- src/components/tag-section/utils.ts
- src/page-templates/main-content-page/content-page-template.tsx
Ticket: https://jira.mongodb.org/browse/DEVHUB-1318
Scope
- Adds a 2nd group of CTA's for Code Example content types to view code on github or try out live site.
- Moves tags to aside view on desktop with labeled grouping -> falls back to original placement of tags below Author Info
- Adds unit test for rendering with labels to `tag-section`
> [DEVHUB-1318]: Improve and Correct the Code Examples Experience

- src/components/seconardynavnew/mobile.test.tsx
- src/components/seconardynavnew/mobile.tsx
[[DEVHUB-1175] Secondary Nav: Mobile - "Topics" should be expanded, and not expandable](https://jira.mongodb.org/browse/DEVHUB-1175)
> [DEVHUB-1175] Secondary Nav Mobile "Topics" expanded and not expandable

- .drone.yml
This is needed based on an advisory from the Kanopy channel.
> Upgrade helm web-app chart to 4.12.0

- src/components/seconardynavnew/desktop.tsx
- src/components/seconardynavnew/dropdown-menu.tsx
[[DEVHUB-1171] Secondary Nav 3 column spacing incorrect (small columns)](https://jira.mongodb.org/browse/DEVHUB-1171)
Previously there was incorrect spacing between columns and within the "All Topics" button of the secondary nav in desktop 
view. This PR fixes these issues, and cleans up some of the styling logic.
> [DEVHUB-1171] Secondary Nav Spacing Fixes

- src/components/article-body/body-components/video-embed.tsx
- src/page-templates/main-content-page/content-page-template.tsx
[[DEVHUB-1431] Must click "play" twice for a video to play](https://jira.mongodb.org/browse/DEVHUB-1431)
Before, there was a thumbnail that had to be clicked on videos:
Now, it displays the video directly from the provider:
> [DEVHUB-1431] Fix having to click twice for videos to play

- next-sitemap.config.js
- package.json
- src/pages/sitemap/sitemap-index.xml.ts
- yarn.lock
[[DEVHUB-1125] NextJS App - Add sitemap](https://jira.mongodb.org/browse/DEVHUB-1125)
Add a sitemap to the site which will reside at [https://mongodb.com/developer/sitemap/sitemap-index.xml](https://mongodb.com/developer/sitemap/sitemap-index.xml) as per the sitemap entry in MongoDB's [main sitemap index file.](https://www.mongodb.com/sitemap.xml)
`next-sitemap` has the ability to generate static sitemaps via a config file, but I didn't use that because of the need for dynamic routes. Their documentation states that in order to have a static and dynamic sitemap in the same app, they must live in separate sitemap files and be referenced by `robots.txt` ([which isn't controlled by this app](https://www.mongodb.com/robots.txt)) and/or referenced by an index sitemap (which also isn't …
> [DEVHUB-1125] Add Sitemap

- environments/prod.yaml
Requests to drone in the webhook were unauthorized because DRONE_TOKEN was undefined at runtime. Only adding to production since staging/preview should not trigger drone events.
> [FIX] Add DRONE_TOKEN to the server for preview webhook

- .drone.yml
- next.config.js
DEVHUB-1501
Upon deployments, new JS files are generated by Next.js which are by default `immutable` but currently Cloudfront caches HTML/document content for one hour. If code changes and updates are added that effect behavior, this will force the browser cache and/or Cloudfront to revalidate the page by adding `must-revalidate` and `proxy-revalidate` directives. 
In addition, decrease the amount of time the page and JS files are cached for so that they remain fresh.
[Recordit](https://recordit.co/) app or …
> [DEVHUB-1501] Adjust cache settings, force revalidation

- next.config.js
Production deploy of https://github.com/mongodb/devcenter/pull/303. This updates the cache settings so that Cloudfront revalidates cached content as well as reduces the max-age so that content is guaranteed to be fresh.
> [DEVHUB-1501] Adjust cache settings, force revalidation (#303)

- src/components/layout.tsx
Link to jira ticket [[DEVHUB-1508](https://jira.mongodb.org/browse/DEVHUB-1508)]
Target `<ul />` in nav for z-index rule instead of parent `<div />` so list options display over secondary nav
N/A
> [DEVHUB-1508]: MongoDB logo in top left doesn't link back to homepage

- src/page-templates/main-content-page/content-page-template.tsx
Link to jira ticket [[DEVHUB-1103](https://jira.mongodb.org/browse/DEVHUB-1103)]
Video type content was missing hyperlink styling
Before:
After:
> [DEVHUB-1103]: Links under videos are not hyperlined

- src/api-requests/get-videos.ts
- src/interfaces/content-item.ts
- src/interfaces/media.ts
- src/page-templates/main-content-page/content-page-template.tsx
- src/service/build-content-items.ts
Link to jira ticket [DEVHUB-1351](https://jira.mongodb.org/browse/DEVHUB-1351)
Displays newly added "Relevant Links" field in Strapi for Video content types
> [DEVHUB-1351]: Add Github URL to "New Videos" collection in strapi/UI

- package.json
- yarn.lock
Once we upgraded to next@12.3.0, we started encountering issues with the preview web hook.
Scroll down [this list ](https://github.com/mongodb/devcenter/settings/hooks/367227055?tab=deliveries) to see that the web hooks started failing at the same time that [this release](https://drone.corp.mongodb.com/mongodb/devcenter/6192/1/1) (which included the next upgrade) happened.   This seems to be happening to some next users, and 7 days ago [someone having this issue with 12.3.0 resolved it by upgrading to 12.3.1](https://github.com/vercel/next.js/discussions/39242#discussioncomment-3697462), so that’s what I’m doing here.
> [FIX] Upgrade to next@12.3.1

- src/components/search/search.tsx
Follow up to https://github.com/mongodb/devcenter/pull/332 which introduced a styling issue on pages with sorting but not filtering. This PR should fix those issues.
> Fix sort by styling on search component

- src/service/get-all-meta-info.ts
[[DEVHUB-1265] Hide documentation link if there is no specific documentation for the topic](https://jira.mongodb.org/browse/DEVHUB-1265)
Topics or content that do not have a specific link to related documentation default to docs.mongodb.com currently. This change is to remove the documentation link altogether when there is no specific related documentation.
Topic without a documentation link
Topic with a documentation link
> [DEVHUB-1265] Hide documentation link if there is no specific documentation for the topic

- lighthouserc.js
- src/components/seconardynavnew/mobile-styles.ts
- src/components/seconardynavnew/mobile.tsx
[[DEVHUB-1218] Secondary Nav: Mobile: Home text should be a link to the homepage, and not open the menu](https://jira.mongodb.org/browse/DEVHUB-1218)
Previously, clicking anywhere on the un-expanded secondary nav in mobile view would open the dropdown, depriving the user of an easy way to navigate back to the homepage. Now, the user can click on the text "MongoDB Developer" to navigate back to the homepage, or click on the chevron if they want to open/close the dropdown. Also, the chevron now encompasses a larger area to make it easier to click on.
-   [ ] I have added tests that prove my fix is effective or …
> [DEVHUB-1218] Secondary Nav Mobile Make Home Text Link To Homepage

- lighthouserc.js
- src/components/seconardynavnew/mobile.tsx
[[DEVHUB-1176] Secondary nav: Mobile - remove chevrons from L1s, and fix spacing between L0 and L1s](https://jira.mongodb.org/browse/DEVHUB-1176)
Chevrons on L1 items were removed.
Before
After
> [DEVHUB-1172] Remove Chevrons From Mobile Secondary Nav Sub-Items

- src/components/seconardynavnew/mobile-styles.ts
[DEVHUB-1557](https://jira.mongodb.org/browse/DEVHUB-1557)
User menu was being center aligned on mobile and tablet viewports. Adding a auto margin to push it over to the right.
> [DEVHUB-1557] fix user menu positioning on mobile/tablet

- next.config.js
Temporarily disabling Sentry. Please see comments in https://jira.mongodb.org/browse/DEVHUB-1558 as to why.
> Disable Sentry temporarily

- src/hooks/search/utils.ts
[DEVHUB-1544](https://jira.mongodb.org/browse/DEVHUB-1544)
Handle when initial content is not being returned since the initial `sortBy` value can be `Most Recent`.
> [DEVHUB-1544] Check default sortBy value in initial content usage logic

- src/hooks/search/meta.ts
N/A 
Found a small bug while poking around staging, when a search page reset its page to 1, the canonical url would reset to `/developer/<slug>/?page=1` instead of just `/developer/<slug>`. This should fix that
> Fix Canonical URL Logic

- .github/workflows/pull-request-checks.yml
https://github.com/actions/runner-images/issues/6399
GitHub is migrating their `ubuntu-latest` image from `20.04` to `22.04` which seems to be breaking playwright. Pinning it to the version that was being used previously for now which should fix the issue.
> Pin ubuntu version to 20.04 for playwright tests in GitHub actions

- src/page-templates/content-page/content-page-template.tsx
[[DEVHUB-1499] Utilize GitHub Octocat](https://jira.mongodb.org/browse/DEVHUB-1499)
Changed the previous external link icon to a GitHub icon for code example pages
Before:
After:
> Change View Code icon to Github Octocat

- .github/workflows/pull-request-checks.yml
Github actions aren't being run on the main branch currently. Percy needs to have a [base build](https://docs.percy.io/docs/baseline-picking-logic#setting-the-projects-default-base-branch) in order to compare PR builds against, the idea being that any code pushed to the base branch is approved visually. By running these checks on the main branch, Percy will consider the build a base build and be able to compare subsequent builds against it.
> Run Github actions on main push for Percy

- src/components/event-widget/event-widget.test.tsx
- src/components/event-widget/event-widget.tsx
- src/components/event-widget/index.tsx
- src/components/event-widget/styles.ts
Link to jira ticket [[DEVHUB-1531](https://jira.mongodb.org/browse/DEVHUB-1531)]
Adding `<EventWidget />` component that will be used in the Industry Events Detail Page. Just adding this component in isolation for now as we work through getting the UI ready for integration once the Event API's are ready.
Using placeholder icons for now, Flora team needs to add the new ones. it's been commented in the code
> [DEVHUB-1531]: Adding Events Widget in scope of Industry Event Details Page

- yarn.lock
Alleviates https://github.com/mongodb/devcenter/pull/387
> [CHORE]: Bump decode-uri-component from 0.2.0 to 0.2.2

- src/components/card-section/featured-card-section.tsx
- src/components/card-section/types.ts
- src/page-templates/content-type-page/content-type.tsx
- src/page-templates/topic-page/topic-page-template.tsx
Link to jira ticket [DEVHUB-1545](https://jira.mongodb.org/browse/DEVHUB-1545)
Changed card sizing in featured card section
before:
after:
> [DEVHUB-1545] Updated featured card sizing

- lighthouserc.js
- src/components/search-filters/desktop/filters.test.tsx
- src/components/search-filters/desktop/filters.tsx
- src/components/search-filters/mobile/filters.test.tsx
- src/components/search-filters/mobile/filters.tsx
- src/data/constants.ts
- src/hooks/search/index.ts
- src/hooks/search/utils.test.tsx
- src/hooks/search/utils.ts
- src/page-templates/content-type-page/content-type-data.ts
[[DEVHUB-1609] Refactor Filtering Logic to be Generic](https://jira.mongodb.org/browse/DEVHUB-1609)
Was going to put this in my events PR but decided to cherry pick it to a separate branch/PR since that PR is getting huge. 
While adding some of the filter/query string logic for events, it felt wrong to add another one-off if statement, so I decided to do some refactoring of the utils to make them completely generic. Now, the source of truth lies in a constant `FILTER_ITEM_MODEL` which declares the order of the filters, the section header names, which filters show on which pages, and which filters group together (L2 items).
Now adding a new filter section should only involve adding an item to the `FILTER_ITEM_MODEL` constant. Also, I felt like these functions could use some tests so I …
> [DEVHUB-1609] Refactor Filtering Utils to be Generic

- README.md
README was missing a field that is needed in your `.env.local` to run SSO locally
> [CHORE]: Update "Running SSO Locally" Section of README 

- src/pages/languages.tsx
- src/pages/products.tsx
- src/pages/technologies.tsx
- src/pages/topics.tsx
- src/service/get-subtopics.ts
[[DEVHUB-1633] Refactor getAllMetaInfo calls to use pre-val](https://jira.mongodb.org/browse/DEVHUB-1633)
Changed all `getAllMetaInfo` calls to use the preval'd version
> [DEVHUB-1633] Refactor getAllMetaInfo calls to use pre-val

- .drone.yml
Fixes a bug where there was a difference between the `REALM_SEARCH_URL` at build time and at run time in staging
> Change Realm Search URLs to Staging Versions in Drone

- src/hooks/search/location.ts
- src/hooks/search/utils.test.tsx
- src/hooks/search/utils.ts
- src/page-templates/topic-content-type-page/topic-content-type-page-template.tsx
- src/pages/api/location.ts
- src/pages/events.tsx
[DEVHUB-1641](https://jira.mongodb.org/browse/DEVHUB-1641)
[DEVHUB-1642](https://jira.mongodb.org/browse/DEVHUB-1642)
[DEVHUB-1643](https://jira.mongodb.org/browse/DEVHUB-1643)
[DEVHUB-1644](https://jira.mongodb.org/browse/DEVHUB-1644)
- Remove Events CTA on Events Topic Content Type pages
- Filter out countries and continents from location search results
- Fix filtering logic. Everything was ORing before, now only filters within each filter group OR, while filters between different filter groups AND (this was the previous behavior in production, this PR should restore that behavior)
- Fix "In-Person" filter bug introduced by previous PR where no results would show up
-   [x] I have …
> [DEVHUB-1641...1644] UAT Events Fixes

- src/page-templates/content-page/content-page-data.ts
- src/page-templates/content-page/content-page-template.tsx
[DEVHUB-1653](https://jira.mongodb.org/browse/DEVHUB-1653)
- Fixes duplicate "Event" titles in Tertiary Nav when an Event has no tags (the child title produces a `events/events` slug which leads to a 404)
> [DEVHUB-1653]: Industry Events Page Shows Parent Events With Child Events In Tertiary Nav

- src/components/event-results/event-results.test.tsx
- src/components/event-results/event-results.tsx
- src/components/event-results/index.ts
- src/hooks/search/meta.ts
- src/hooks/search/types.ts
- src/page-templates/content-type-page/content-type-body.tsx
- src/page-templates/content-type-page/content-type-template.tsx
- src/page-templates/topic-content-type-page/topic-content-type-page-template.tsx
- src/page-templates/topic-page/topic-page-template.tsx
- src/pages/events.tsx
- src/pages/search.tsx
[DEVHUB-1645](https://jira.mongodb.org/browse/DEVHUB-1645)
- Extract the events page's multi-tiered results to its own component
- Add tests for new component
- Consume the new component in the events page and also in the topic content type page
- During this work, I noticed I was doing a lot of passing around search-meta-related props unnecessarily, so I added them to the `useSearchMeta` hook to cut down on prop passing
> [DEVHUB-1645] Match Topic Content Type Events Page Results to Main Events Page

- src/components/event-widget/event-widget.test.tsx
- src/components/event-widget/event-widget.tsx
- src/utils/format-date.ts
[DEVHUB-1662](https://jira.mongodb.org/browse/DEVHUB-1662)
Formats Event Dates based on UAT feedback
On Events Page:
On Detail Page:
> [DEVHUB-1662]: The "When" field doesn't need times when it's a multi-day event

- src/components/card/card.tsx
- src/components/icons/event-icon/event-icon.tsx
- src/components/search/results.tsx
- src/hooks/search/index.ts
- src/utils/is-server-side.ts
For SEO reasons, results should be generated statically in the build output, as well as dynamically, which can be verified by disabling javascript. Previously, doing so resulted in a "No Results" screen on the Events page, but this PR should fix that issue. I also created a utility function `isServerSide()` instead of checking `typeof window === 'undefined'` every time.
> Fix Events Results not showing when JavaScript is disabled

- src/page-templates/content-page/content-page-template.tsx
Link to jira ticket [DEVHUB-1671](https://jira.mongodb.org/browse/DEVHUB-1671)
Looks like `cardType` prop was missing from `twitter` in `<NextSEO />`. Need to test out on staging for 100% confirmation
> [DEVHUB-1671]: Twitter Preview Card Not visible 

- src/components/search/types.ts
- src/components/search/utils.ts
- src/page-templates/content-type-page/content-type-data.ts
[DEVHUB-1681](https://jira.mongodb.org/browse/DEVHUB-1681)
Already added a new sort order in the Realm search function. After talking with Mike, there's no real use case for that "nearest to the current date" logic, so this new sort mode is just the inverse of "Newest".
> [DEVHUB-1681] Add new sort order for events.

- src/components/recommended-section/additional-content-placeholder.tsx
- src/components/recommended-section/recommended-content-section.tsx
- src/components/recommended-section/recommended-section.test.tsx
- src/components/recommended-section/recommended-section.tsx
- src/components/recommended-section/recommended-tag-section.tsx
Follow up to https://github.com/mongodb/devcenter/pull/439, this fixes some styling issues and adds in some things I missed in that PR (mainly, adding arrows that trigger the personalization modal opening)
> Fixes for Recommendation Section

- environments/prod.yaml
- environments/staging.yaml
- src/components/follow-link/follow-link.tsx
- src/components/modal/personalization/utils.ts
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/userPreferences.ts
- src/utils/refresh-session.ts
Partially related to [DEVHUB-1606](https://jira.mongodb.org/browse/DEVHUB-1606).
Implements the backend connectivity for the FollowLink component. There were some weird things about this:
* Added a hacky way to refresh the session manually. It is imperfect though since it just emits an event on the browser and we can't await the refresh.
* Added an extra state `isShowingFollowing` to manually control what the link displays. This was necessary because after we make the API call to update the user, we trigger an event to refresh the session. However, we have no way of knowing when the new request to get the session will complete, since it is just triggered by an event we emit. In order to avoid sync issues between the button text and the tooltip text, I created this state to provide a clean …
> [DEVHUB-1606] Fix backend compatibility, fix follow-link functionality.

- src/components/modal/personalization/paginated/personalization-paginated.modal.tsx
- src/components/modal/personalization/scroll/personalization-scroll.modal.tsx
- src/components/modal/personalization/utils.ts
- src/components/notification/index.ts
- src/components/notification/notification.tsx
- src/components/notification/styles.ts
- src/contexts/notification.tsx
- src/pages/_app.tsx
- src/pages/api/userPreferences.ts
- src/types/notification-type.ts
[DEVHUB-1701](https://jira.mongodb.org/browse/DEVHUB-1701)
- Adds `<Notification />`, `<NotificationContainer />` component and context to display notifications based on relevant HTTP success/errors. `<Notification />` can be used anywhere in the app to display a static notification, whereas `<NotificationContainer />` leverages `useNotificationContext` and displays notifications in the bottom lefthand corner and auto-dismisses after 2 seconds (note: this timeout number might have to be increased after trying it out on local).
STILL NEEDS TO BE DONE:
- Added to remaining places in scope of personalization changes
- Unit test(s) for notification component and contexts
-   [x] I have …
> [DEVHUB-1701]: Toast components for personalization error states

- src/components/modal/personalization/paginated/personalization-paginated.modal.tsx
- src/components/modal/personalization/scroll/personalization-scroll.modal.tsx
- src/components/modal/personalization/utils.ts
- src/components/notification/index.ts
- src/components/notification/notification.tsx
- src/components/notification/styles.ts
- src/components/recommended-section/recommended-section.test.tsx
- src/components/recommended-section/recommended-section.tsx
- src/components/recommended-section/recommended-tag-section.tsx
- src/contexts/notification.tsx
- src/hooks/personalization/index.ts
- src/pages/_app.tsx
- src/pages/api/userPreferences.ts
- src/pages/index.tsx
- src/types/notification-type.ts
Quick fix/follow up to https://github.com/mongodb/devcenter/pull/448
Bringing up the personalization modal when a user has followed topics would always display no tags selected. Now, the tags initially selected should reflect what the user is currently following.
edit: also fixed caching behavior that was noticed with recommended content endpoint
> Fix for Recommended Content Modal

- next-auth.d.ts
- src/components/follow-link/follow-link.tsx
- src/components/layout.tsx
- src/components/modal/personalization/paginated/personalization-paginated.modal.tsx
- src/components/modal/personalization/scroll/personalization-scroll.modal.tsx
- src/components/modal/personalization/utils.ts
- src/components/recommended-section/recommended-section.tsx
- src/hooks/personalization/index.ts
- src/hooks/personalization/user-preferences.ts
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/personalized-content.ts
- src/pages/api/userPreferences.ts
- src/pages/index.tsx
[DEVHUB-1703](https://jira.mongodb.org/browse/DEVHUB-1703)
- Added a hook (`useUserPreferences`) to utilize the notification context whenever updating preferences.
- Added `failedToFetch` flag on the session object to indicate that we failed to find the user's information.
- Adjust `submitPersonalizationSelections` to throw errors consistently.
- Used these to implement notifications.
- Also adjusted the `Cache-Control` header on personalization endpoints to invalidate the browser cache when sending a bad response. I was having some issues with this and the SWR cache, but it seems to work now.
> [DEVHUB-1703] Implement remaining notifications.

- src/components/recommended-section/recommended-section.test.tsx
- src/components/recommended-section/recommended-section.tsx
- src/components/recommended-section/recommended-tag-section.tsx
Lifted the selected tags state from the recommended tag section into its parent. Before, the state was being tracked twice, which caused this out-of-sync bug. Also added a test for this case.
> Fix Recommended Tags Section not syncing with Personalization Modal

- lighthouserc.js
- playwright-tests/pages/[...slug].spec.ts
- src/page-templates/content-page/content-page-data.ts
- src/page-templates/content-page/content-page-template.tsx
- src/page-templates/content-page/util.ts
Link to jira ticket [DEVHUB-1111](https://jira.mongodb.org/browse/DEVHUB-1658)
Breadcrumbs, Tertiary Nav, and Follow Topic Button can be broken when a `contentItem` has no primary tag (i.e.,`l_1_product`, `programming_language`, `technology`). More details can be found in the Screenshots section below.
1. BreadCrumb: Incorrect topic link can be rendered 
- Currently Incorrect State ([Podcast Example](https://www.mongodb.com/developer/podcasts/dwight-merriman-and-lena-smart/)): https://www.mongodb.com/developer/topics/podcasts/
- Corrected State: https://podcasts.mongodb.com/ based on Liz's comment on the [ticket](https://jira.mongodb.org/browse/DEVHUB-1658)
2. Tertiary Nav: Duplicate link may appear
- Currently Incorrect State ([Podcast …
> [DEVHUB-1658] Fix breadcrumb, tertiary nav, follow-topic button when there is no primary tag

- .eslintrc.json
- next.config.js
[DEVHUB-1696](https://jira.mongodb.org/browse/DEVHUB-1696)
Followup to https://github.com/mongodb/devcenter/pull/475.
PathFactory could not embed our content on https://mongodbcom.website.prod.corp.mongodb.com because we have the `X-Frame-Options` header set to `SAMEORIGIN` for all pages. I added the `Content-Security-Policy` header's `frame-ancestors` attribute, which adds more control to embedding behavior. I set it to allow embedding from all subdomains of mongodb.com, as well as from the same origin.
Also disabled an ESLint rule affecting the next.config.js file.
> [DEVHUB-1696] Set CSP headers to allow embedding from *.mongodb.com.

- config/redirects.json
https://jira.mongodb.org/browse/DEVHUB-1691
Opening this PR directly to production since main has Mongodb TV code - which we do not want to push to production yet.
> Devhub-1691 Adding redirect

- src/service/get-all-podcasts.ts
- src/service/get-all-videos.ts
[DEVHUB-1797](https://jira.mongodb.org/browse/DEVHUB-1797)
We manually add content type tags for Videos and Podcast, and we were still adding them in the old format. This was causing them not to be picked up by various other logic.
> [DEVHUB-1797] Fix added Video and Podcast content type tag format

- src/components/secondary-nav/desktop.tsx
Due to Flora changes, the Link component no longer stops event propagation by default. This meant that our event listener that checks for clicks outside the dropdown to close it was registering and was closing the menu immediately after opening.
> Add stopPropagation to prevent menu from clsoing itself.

- playwright-tests/pages/[...slug].spec.ts
- src/api-requests/contentstack_utils.ts
- src/api-requests/get-articles.ts
- src/api-requests/get-industry-events.ts
- src/pages/preview/[...slug].tsx
- src/service/get-preview-content.ts
- src/utils/client-factory.ts
[DEVHUB-1807](https://jira.mongodb.org/browse/DEVHUB-1807)
1. Updated `fetchAll()` to have a `fetchPolicy`; for staging-related requests, `no-cache` is used to avoid stale responses
2. Changed ApolloClient from GET (with URI encoding) to POST (default option) to avoid occasional URI-too-long error code from Contentstack
3. Updated UI to render 404 page (instead of a 5xx error) when a content is not found, which happens when a preview content is not found
> [DEVHUB]-1807 Stale Responses from ContentStack Graphql API's impacting previews

- src/service/build-content-items.ts
- src/utils/contentstack.ts
[DEVHUB-1685](https://jira.mongodb.org/browse/DEVHUB-1685)
- I have manually tested this [page](https://www.mongodb.com/developer/products/atlas/email-password-authentication-react/). Before this PR, there was no `<meta property="og:image">`.
- According to the [Next-SEO documentation](https://github.com/garmeeh/next-seo), _Twitter will read the og:title, og:image and og:description tags for their card. next-seo omits twitter:title, twitter:image and twitter:description to avoid duplication._
- Now that og:image shows up, the issue should hopefully be fixed; I think I can only test this (i.e., sharing onto Twitter) once this is deployed to prod; @mcolella14 let me know if you think otherwise
> [DEVHUB-1685] Fetch og_images for SEO

- src/graphql/articles.ts
- src/page-templates/content-page/content-page-template.tsx
- src/service/build-content-items.ts
- Provide a default `og:type` of `article` or `video:other` when appropriate.
- Add missing GraphQL twitter-related fields.
- Add `publishedTime`, `modifiedTime`, and `authors` for articles.
> Add more SEO fields

- src/graphql/authors.ts
- [Fix the ApolloError in Sentry](https://jira.mongodb.org/browse/DEVHUB-1907)
- Fix a typo which causes corrupted `gql` syntax and leads to `ApolloErrors`
> [DEVHUB-1907] fix(sentry): Patch apollo error due to incorrect graphql syntax

- src/utils/markdown-parser/convert-references.ts
const markdownWithInLine = await remark()
.use(remarkInlineLinks)
.process(markdownWithReferences);
is breaking youtube embeddings , the above is a patch to undo the change introduced to youtube embeddings while converting references to inline links.
> adding fix for youtube wrong rerender

- src/service/build-content-items.ts
- src/service/get-all-authors.ts
- [Fix the image destructure issue in Sentry](https://jira.mongodb.org/browse/DEVHUB-1923)
- Update the code to handle the case when `node = undefined`.
> [DEVHUB-1923] fix(sentry-issues): Fix destructure image issue
