- src/components/grid.tsx
- src/interfaces/components/grid.ts
- src/pages/index.tsx
- src/pages/topics/[slug].tsx
- src/pages/topics/index.tsx
- src/styled/grid.tsx
- src/styled/theme.ts
- Created Grid component.
- Added routes and pages for `/topics` and `/topics/L1`, which shows the grid layout.
https://user-images.githubusercontent.com/46664803/149998226-e1cba09e-22ed-49b5-886c-8b490c6226c4.mov
> [DEVHUB-957] L1 topic skeleton

- .babelrc
- .prettierignore
- README.md
- package.json
- src/README.md
- src/styled/consistent-nav.tsx
- src/styled/theme.ts
The main change here is adding `src/README.md` to explain the file structure. I also expanded the files that prettier affects, so the other changes are mostly formatting along with some cleaning up of imports.
> Add to readme and cleanup

- .github/dependabot.yml
- .prettierignore
This will let dependabot make PRs for any package updates, not just security-related ones.
> add dependabot.yml file

- package.json
- yarn.lock
Fixes node-fetch vulnerability.
> Use next@canary until next release.

- .github/workflows/pull-request-checks.yml
- .github/workflows/vercel-deploy.yml
- lighthouserc.js
- next.config.js
Adding vercel deployment workflow
> DEVHUB-976 testing vercel deploy

- src/components/search/index.ts
- src/components/topic-card/index.ts
- src/components/topic-card/styles.ts
- src/components/topic-card/topic-card.test.tsx
- src/components/topic-card/topic-card.tsx
- src/components/topic-card/topic-cards-container.test.tsx
- src/components/topic-card/topic-cards-container.tsx
- src/components/topic-card/types.ts
- src/pages/topics/[slug].tsx
[JIRA Ticket](https://jira.mongodb.org/browse/DEVHUB-997)
I also reorganized the search component exports to export from `index.ts` for simplicity.
> [DEVHUB-997] Topic Cards

- src/components/card/card.test.tsx
- src/components/card/card.tsx
- src/components/card/types.ts
- src/components/card/utils.ts
- src/components/feedback-modal/dialogs/text-feedback.tsx
- src/components/feedback-modal/dialogs/thank-you.tsx
- src/components/feedback-modal/feedback-modal.tsx
- src/components/feedback-modal/index.ts
- src/components/request-content-modal/dialogs/text-request.tsx
- src/components/request-content-modal/dialogs/thank-you.tsx
- src/components/request-content-modal/index.ts
- src/components/request-content-modal/request-content-modal.test.tsx
- src/components/request-content-modal/request-content.modal.tsx
- src/components/request-content-modal/styles.ts
- src/components/request-content-modal/types.ts
- src/components/series-card/index.ts
- src/components/series-card/series-card.test.tsx
- src/components/series-card/series-card.tsx
- src/components/series-card/styles.ts
- src/components/series-card/types.ts
- src/interfaces/content-piece.ts
- src/pages/[...slug].tsx
- src/requests/get-series.ts
[Jira Ticket](https://jira.mongodb.org/browse/DEVHUB-1015)
The main components here are the `SeriesCard` and `RequestContentModal`.  I did make some minor changes to other areas:
- Changed the `href` prop on the `Card` component to `slug` to be more explicit about what to render, because the behavior of `next/link` gets confused by our routing.
- Made some styling changes to the `FeedbackModal` to keep it in line with what I did in `RequestContentModal`.
> Devhub 1015/article content footer

- src/components/series-card/series-card.test.tsx
- src/components/series-card/series-card.tsx
- src/components/series-card/series-list.tsx
- src/components/series-card/styles.ts
[Jira Ticket](https://jira.mongodb.org/browse/DEVHUB-1057)
Basically just copied the styles from the Flora component and added links as items.
> Make series card list with links

- src/api-requests/get-all-podcasts.ts
- src/api-requests/get-all-videos.ts
- src/components/card/card.test.tsx
- src/components/card/card.tsx
- src/components/podcast-player/podcast-player.tsx
- src/interfaces/media.ts
- src/interfaces/podcast.ts
- src/pages/[...slug].tsx
- src/service/get-all-content.ts
- src/utils/get-place-holder-thumbnail.ts
This PR replaces the place holders in podcast and video pages with podcast player and Youtube players.
https://devcenter-nf9z21p1d-harikakotipalli.vercel.app/videos/compass---the-gui-for-mongodb-in-10-mins----jumpstart
https://devcenter-nf9z21p1d-harikakotipalli.vercel.app/podcasts/ep--102-changing-the-game-with-mongodb
> devhub-1044  podcast and video players

- environments/prod.yaml
- environments/staging.yaml
- next.config.js
This feature does not work properly (with the current state of the application) and will need to be revisited.
> Remove rewrites entirely

- .drone.yml
- .github/workflows/pull-request-checks.yml
- README.md
- cypress.json
- environments/staging.yaml
- next.config.js
- src/components/content-rating/content-rating.tsx
- src/components/social-buttons/social-buttons.tsx
- src/pages/_app.tsx
Update the basePath of our app to `/developer` for the Kanopy team and for this to coincide with /developer.
> Update base path for Kanopy

- src/lib/gtm.js
- src/pages/_app.tsx
- src/pages/_document.tsx
> [DEVHUB-1111] Added GTM to NextJS

- src/api-requests/get-all-podcasts.ts
- src/api-requests/get-all-videos.ts
- src/api-requests/get-articles.ts
- src/interfaces/article.ts
- src/interfaces/content-item.ts
- src/interfaces/media.ts
- src/interfaces/seo.ts
- src/pages/[...slug].tsx
- src/service/get-all-content.ts
this pr addresses SEO details for 
https://jira.mongodb.org/browse/DEVHUB-1123
1. <title tag> are duplicative across most of the pages. Should also append " | MongoDB" at the end, eg: Python Tutorials | MongoDB
2. <meta description> are duplicative across most of the pages
> Devhub 1131 - adding seo data from strapi

- src/pages/languages.tsx
Add fourth featured language to developer/languages
> [DEVHUB-1188] Add fourth featured language

- src/data/homepage.ts
- src/data/secondary-nav.ts
- src/service/get-all-meta-info.ts
Jira Ticket:
[DEVHUB-1241](https://jira.mongodb.org/browse/DEVHUB-1241)
> Minor 404 fixes, change primary CTA text

- src/pages/technologies.tsx
Changed FlashCard component with TopicCard component. 
**Before:**
**After:**
> [DEVHUB-1249] Modify technologies page

- src/components/card/card.tsx
- src/components/card/types.ts
- src/components/search/results.tsx
- src/components/search/search.tsx
- src/components/search/types.ts
- src/page-templates/content-type/content-type.tsx
- src/pages/[...slug].tsx
- src/pages/[l1_l2]/[...slug].tsx
- src/pages/[l1_l2]/[topic]/[...slug].tsx
- src/pages/author/[...slug].tsx
- src/pages/search.tsx
Jira tickets:
- [DEVHUB-1242](https://jira.mongodb.org/browse/DEVHUB-1242)
- [DEVHUB-1232](https://jira.mongodb.org/browse/DEVHUB-1232)
- [DEVHUB-1110](https://jira.mongodb.org/browse/DEVHUB-1110)
- [DEVHUB-1251](https://jira.mongodb.org/browse/DEVHUB-1251)
- [DEVHUB-1252](https://jira.mongodb.org/browse/DEVHUB-1252)
> mc UAT batch 4

- src/api-requests/get-all-meta-info.ts
- src/components/tertiary-nav/types.ts
- src/data/constants.ts
- src/interfaces/meta-info.ts
- src/pages/[...slug].tsx
- src/pages/[l1_l2]/[...slug].tsx
- src/pages/[l1_l2]/[topic]/[...slug].tsx
- src/service/get-all-meta-info.ts
- src/utils/add-documentation-link-to-side-nav.tsx
[DEVHUB-1120](https://jira.mongodb.org/browse/DEVHUB-1120)
> devhub-1120 documentation link to side nav

- src/pages/author/[...slug].tsx
in reference to https://mongodb.slack.com/archives/C02NFHPSZ6Z/p1653491029496949
> removing load more functionality from author pages to make content discoverable

- src/components/card/card.tsx
- src/components/search/results.tsx
- src/components/search/search.tsx
- src/page-templates/content-type/content-type.tsx
- src/pages/search.tsx
The rating-star svg seems fine, think it might not affect SVGs.
> Add thumbnail loader to all images that need it.

- config/redirects.json
Remove /learn redirect which was causing issues testing CDN with Angelo.
> Remove /learn redirect causing issues

- src/components/article-body/body-components/paragraph.tsx
> [DEVHUB-1226] Paragraph copy needs to wrap/break

- package.json
- src/api-requests/get-articles.ts
- src/components/social-buttons/copy-link.tsx
- src/components/social-buttons/social-buttons.tsx
- src/components/social-buttons/styles.ts
- src/components/social-buttons/utils.ts
- src/pages/[...slug].tsx
- src/service/get-all-meta-info.ts
- src/utils/technology-to-logo.ts
- yarn.lock
Jira Tickets:
- [DEVHUB-981](https://jira.mongodb.org/browse/DEVHUB-981)
- [DEVHUB-1259](https://jira.mongodb.org/browse/DEVHUB-1259)
- [DEVHUB-1276](https://jira.mongodb.org/browse/DEVHUB-1276)
> mc/Miscellaneous Pre-World things.

- yarn.lock
> Bump semver-regex

- src/pages/author/[...slug].tsx
Not sure how this happened, but the author page is missing? Adding it back
> Add author page

- src/pages/_middleware.ts
- src/utils/rate-limit.ts
Trying to debug on staging, but I need some output to see why it's not working.
> Add logs for rate limiting and blocking requests

- src/utils/product-to-logo.ts
Added "Aggregation Framework" in product-to-logo before testing change in Strapi
> added Aggregation Framework mapping to product-to-logo

- src/components/article-body/body-components/codeblock.tsx
[DEVHUB-1228](https://jira.mongodb.org/browse/DEVHUB-1228)
> [DEVHUB-1228] Fix scrolling code block border radius

- src/page-templates/main-content-page/content-page-template.tsx
[DEVHUB-1287](https://jira.mongodb.org/browse/DEVHUB-1287)
> [DEVHUB-1287] Remove news and announcements request modal.

- src/data/homepage.ts
- src/pages/index.tsx
[DEVHUB-1342](https://jira.mongodb.org/browse/DEVHUB-1342)
> [DEVHUB-1342] Remove java homepage code examples link

- src/components/seconardynavnew/mobile-styles.ts
- src/components/seconardynavnew/mobile.tsx
[DEVHUB-1167](https://jira.mongodb.org/browse/DEVHUB-1167)
> [DEVHUB-1167] Fix mobile nav scrolling issues

- .drone.yml
Since staging is now refreshed, update staging environment variables.
> Update Strapi env vars for staging

- .dockerignore
- .drone.yml
- .gitignore
- .prettierignore
- Dockerfile
- environments/prod.yaml
- environments/staging.yaml
- next.config.js
- package.json
- sentry.client.config.ts
- sentry.properties
- sentry.server.config.ts
- src/components/error-boundary.tsx
- src/pages/_app.tsx
- src/pages/_error.tsx
- src/pages/api/createFeedback.ts
- src/pages/api/health.js
- src/pages/api/preview-build-webhook.ts
- src/pages/api/requestContent.ts
- src/pages/api/search.ts
- src/pages/api/updateFeedback.ts
- yarn.lock
- Improve drone pipeline by removing need for build args (student app does something similar, so most of the Drone pipeline code is taken from there).
- Adds Sentry monitoring to the project: includes ErrorBoundary, hooks on API handlers and handling on all error pages.
> [DEVHUB-1356] Implement and Configure Sentry IO into Developer Center

- .drone.yml
Removes unnecessary configuration and steps from the Drone pipeline.
> Cleanup drone pipeline

- .drone.yml
- .github/workflows/pull-request-checks.yml
- environments/prod.yaml
- environments/staging.yaml
- src/utils/client-factory.ts
> [DEVHUB-1392] Update devcenter endpoints

- package.json
- src/components/card/styles.ts
- src/components/showcase-card/showcase-card.tsx
- yarn.lock
Mainly to get a fix out for the UI issue mentioned here https://jira.mongodb.org/browse/DEVHUB-1430
> Release 2022-08-02

- public/googlef8aa02d077bb15d6.html
Adds Google site verification file as per https://jira.mongodb.org/browse/DEVHUB-1432.
> [DEVHUB-1432] Add Google site verification file

- next.config.js
- package.json
- src/pages/_middleware.ts
- src/pages/api/revalidate-webhook.ts
- yarn.lock
* Downgrade Next.js back to 12.1.0
> Release 2022-08-08

- config/redirects.json
- config/rewrites.js
[DEVHUB-1433](https://jira.mongodb.org/browse/DEVHUB-1433)
This can be merged after the new academia site is deployed.
> [DEVHUB-1433] - Add academia redirects for new academia portal.

- src/components/seconardynavnew/desktop.tsx
- src/data/secondary-nav.ts
Noticed that these aren't really supposed to be there (not in design).
Edit: Topic shouldn't be underlined, but homepage should be.
> Remove underline for Topics on homepage

- README.md
Clarifying how to run SSO locally since this came up earlier.
> Add README for SSO local login

- sentry.client.config.ts
- sentry.server.config.ts
- src/hooks/search/utils.test.tsx
- src/hooks/search/utils.ts
- src/page-templates/content-type/content-type.tsx
DEVHUB-1501
Rachelle reported an issue with content type page (videos) not loading search content data. This has not been replicable on my end or for others in the group, so I am adding Sentry logging and checking for empty result data.
> [DEVHUB-1501] Handling empty results and error logging in Sentry

- PULL_REQUEST_TEMPLATE.md
- environments/prod.yaml
- environments/staging.yaml
- sentry.client.config.ts
- sentry.server.config.ts
- src/hooks/search/utils.test.tsx
- src/hooks/search/utils.ts
- src/page-templates/content-type/content-type.tsx
Scheduled release to resolve a hard to replicate bug (DEVHUB-1501) along with minor fixes relating to technical debt.
> Release 09-13-22

- src/components/search/utils.test.tsx
- src/components/search/utils.ts
- src/page-templates/content-type/content-type.tsx
- src/page-templates/topic-content-type-page/topic-content-type-page-template.tsx
- src/page-templates/topic-page/topic-page-template.tsx
- src/pages/[...slug].tsx
- src/pages/_app.tsx
- src/pages/articles.tsx
- src/pages/author/[name].tsx
- src/pages/code-examples.tsx
- src/pages/news.tsx
- src/pages/podcasts.tsx
- src/pages/quickstarts.tsx
- src/pages/search.tsx
- src/pages/tutorials.tsx
- src/pages/videos.tsx
- src/utils/page-type-factory.ts
- src/utils/seo.js
…e setting
DEVHUB-1497
These are fast follow fixes for SEO related findings that Elizabeth shared with me.
They include the following:
- Pull in the same meta description as the main page for the paginated pages and maybe add “topic - page x” in there
- For pages that don't exist, return 404 rather than the first / last page.
- Fix issue with author route which can allow a repeating name in the URL (https://www.mongodb.com/developer/author/sourabh-bagrecha/sourabhbagrecha/)
-   [x] I have added tests that prove my fix is effective or that my feature works (SEO …
> [DEVHUB-1497] Meta description page no, fix author page dynamic route

- .drone.yml
None
Restore the former App Services endpoint for staging at build time.
> Replace App Services endpoint location

- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/articles.tsx
- src/pages/code-examples.tsx
- src/pages/news.tsx
- src/pages/podcasts.tsx
- src/pages/quickstarts.tsx
- src/pages/search.tsx
- src/pages/tutorials.tsx
- src/pages/videos.tsx
[DEVHUB-1247](https://jira.mongodb.org/browse/DEVHUB-1247)
- Add dns-prefetch and preconnect tags based on best practices (https://support.optimizely.com/hc/en-us/articles/4410289759629-Best-practices-for-improving-site-performance-with-Optimizely). 
- Make scripts async (https://support.optimizely.com/hc/en-us/articles/4410289847053-Synchronous-and-asynchronous-snippet-loading)
- Updating the noscript block to use `dangerouslySetInnerHTML` for the performance gains. (This is commonly used in examples of implementing GTM with Next.js)
- Also found an unrelated bug that I noticed on account of this test failure (https://github.com/mongodb/devcenter/actions/runs/3101300320/jobs/5022514715). Seems to happen if initial content is an empty list. …
> [DEVHUB-1247] Try to improve page latency - Part 2

- src/pages/_document.tsx
Reverting this change from https://github.com/mongodb/devcenter/pull/317 as it doesn't seem to make a difference.
> Revert iframe update

- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/articles.tsx
- src/pages/code-examples.tsx
- src/pages/news.tsx
- src/pages/podcasts.tsx
- src/pages/quickstarts.tsx
- src/pages/search.tsx
- src/pages/tutorials.tsx
- src/pages/videos.tsx
Production release for Sept. 22.
* Improve site perf due to Optimizely
* Use dns-prefetch and preconnect for GTM and Optimizely scripts
* Load optimizely snippet asynchronously
* Revert back to beforeInteractive
* Add async to scripts
* Fix issue where initial content is empty
> Release 09-22-22

- src/components/seconardynavnew/desktop.tsx
- src/components/seconardynavnew/mobile.tsx
- src/components/seconardynavnew/tracking.tsx
[[DEVHUB-1422] Add tracking to Secondary Nav](https://jira.mongodb.org/browse/DEVHUB-1422)
Segment tracking calls added to opening/closing the secondary nav as well as clicking links within it.
Tracking events showing up in Segment debugger:
https://user-images.githubusercontent.com/110849018/191844652-5d6aee2e-89c0-417c-96ef-91c2c8639090.mov
Tracking events showing up in Google Analytics dashboard (this one's a bit more delayed):
https://user-images.githubusercontent.com/110849018/191844686-9a37be90-1824-4a5d-9573-2afe64c7995b.m …
> [DEVHUB-1422] Secondary Nav Tracking

- src/pages/_document.tsx
[DEVHUB-1514](https://jira.mongodb.org/browse/DEVHUB-1514)
Based on page latency reports, Eric has provided me with a new script for Optimizely that might speed things up.
> [DEVHUB-1514] Swap out Optmizely script with .com analytics removed

- src/api-requests/get-videos.ts
- src/interfaces/content-item.ts
- src/interfaces/media.ts
- src/page-templates/main-content-page/content-page-template.tsx
- src/pages/_document.tsx
- src/service/build-content-items.ts
Production release for 9/27/22.
> Release 09-27-22

- next.config.js
- package.json
- src/components/search-filters/filter-group.tsx
- src/components/search-filters/mobile/filters.test.tsx
- src/components/search-filters/mobile/filters.tsx
- src/components/search-filters/styles.ts
- src/components/search-filters/types.ts
- src/components/search/search.tsx
- src/components/search/styles.ts
- src/components/search/types.ts
- src/hooks/search/utils.ts
- src/page-templates/content-type/content-type.tsx
- src/page-templates/content-type/styles.ts
- src/pages/search.tsx
- yarn.lock
Link to jira ticket [[DEVHUB-1428](https://jira.mongodb.org/browse/DEVHUB-1428)]
> [DEVHUB-1428]: Add Sort By To Top Level Pages

- .drone.yml
- environments/preview.yaml
As a part of [DEVHUB-1506](https://jira.mongodb.org/browse/DEVHUB-1506), I need to fix the preview environment.
Adding environment variables needed for the preview environment and adjusting the config accordingly.
> [DEVHUB-1506] Configure env for preview

- lighthouserc.js
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/utils/gtm.js
[DEVHUB-1337](https://jira.mongodb.org/browse/DEVHUB-1337)
Removed all GTM-related code, added new script.
> [DEVHUB-1337] Remove GTM scripts, add new pathway.js script

- src/pages/search.tsx
[DEVHUB-1549](https://jira.mongodb.org/browse/DEVHUB-1549)
Adjusted the structure of the Search page filter tags to align with the Content Type page structure.
> [DEVHUB-1549] Fix search page filter tag alignment

- src/middleware.ts
- src/pages/api/405.ts
- src/pages/api/429.ts
Production deploy for DEVHUB-1558.
> [DEVHUB-1558] Fix issue in Kanopy channel (#343)

- config/redirects.json
[https://jira.mongodb.org/browse/DEVHUB-1498](https://jira.mongodb.org/browse/DEVHUB-1498)
Add redirect for an article that used to exist on the old Devhub site.
> [DEVHUB-1498] Add redirect for bookmarked 404 page

- config/redirects.json
[[DEVHUB-1518] New Slug & 301 Redirect for Cloudflare](https://jira.mongodb.org/browse/DEVHUB-1518)
Adding a redirect from old article URL to a new one
> [DEVHUB-1518] Add redirect for Cloudflare REST API Realm article

- package.json
- src/hooks/search/index.ts
- yarn.lock
Link to jira ticket [[DEVHUB-1474](https://jira.mongodb.org/browse/DEVHUB-1474)]
Upgrade Flora Version after their latest release, which includes stable version/release of `<RadioGroup />`
> [DEVHUB-1474]: Radio Button Flora Contribution

- src/utils/technology-to-logo.ts
[DEVHUB-1468](https://jira.mongodb.org/browse/DEVHUB-1468)
> [DEVHUB-1468] - Add Spring logo

- src/pages/languages.tsx
- src/pages/products.tsx
Adds prop to fix breaking change from Flora Flash Card Component
Before:
After:
> [HOTFIX]: Fix Flora <FlashCard /> Breaking Change

- package.json
- yarn.lock
[DEVHUB-1582](https://jira.mongodb.org/browse/DEVHUB-1582)
> [DEVHUB-1582] Bump devcenter-components for bug fix

- config/redirects.json
[DEVHUB-1395](https://jira.mongodb.org/browse/DEVHUB-1395)
Add redirect for data lake -> data federation article.
> [DEVHUB-1395] Add redirect for query-multiple-databases-with-atlas-data-federation

- yarn.lock
None
Addresses:
CVE-2022-37601
CVE-2022-37603
CVE-2022-37599
> Bump loader-utils from 2.0.2 to 2.0.4

- package.json
- src/components/search-filters/mobile/filters.tsx
- src/components/search/styles.ts
- src/components/tertiary-nav/tertiary-nav.tsx
- src/page-templates/content-type/content-type.tsx
- yarn.lock
This PR fixes a couple of issues introduced to production by the last release + several pre-existing styling issues:
- Fixed sort by option not showing up in mobile sorting menu
- Fixed featured card sections being larger than their containers on mobile
- Fixed sort by dropdown options being larger than the parent box, causing a layout shift while viewing topic/topic-content-type pages on mobile and trying to sort
- Fixed styling issue on content-type pages where the Topics chevron and the filter checkboxes were smaller than they were supposed to be. This was due to a theme-ui `ThemeProvider` being added to the `Lightbox` component, and was fixed by updating the version of `theme-ui` to the one that flora uses (`0.13.1`)
- Fixed styling issue on pages with tertiary nav on mobile where the …
> Fix Various Styling Issues + Mobile Sortby

- environments/prod.yaml
None
Increase max replicas on production.
> Increase max replicas on production

- config/redirects.json
[DEVHUB-1345](https://jira.mongodb.org/browse/DEVHUB-1345)
Will change the slug in Strapi when this is deployed.
> [DEVHUB-1345] Add redirect for typo

- src/components/showcase-card/showcase-card.tsx
Link to jira ticket [DEVHUB-1237](https://jira.mongodb.org/browse/DEVHUB-1237)
Changed font size to 20px for language and product showcase cards on home page
> [DEVHUB-1237] Font size changes on home page

- src/components/seconardynavnew/dropdown-menu.tsx
[DEVHUB-1535
](https://jira.mongodb.org/browse/DEVHUB-1535)
Added back hidden links in the dropdown menu
NA
-   [X] I have performed a self-review(QA) of my code and reviewed with Design or Product (If Applicable)?
> [DEVHUB-1535] Added back hidden links

- playwright-tests/pages/[...slug].spec.ts
- src/components/request-content-modal/dialogs/text-request.tsx
- src/components/request-content-modal/request-content-modal.test.tsx
Link to jira ticket [DEVHUB-1567](https://jira.mongodb.org/browse/DEVHUB-1567)
Added invalid state to Topic and Description fields on the article request modal
> [DEVHUB-1567] Prevent empty submissions for article requests

- package.json
- src/components/event-widget/event-widget.tsx
- src/components/location-search/location-search.tsx
- yarn.lock
Link to jira ticket [DEVHUB-1573](https://jira.mongodb.org/browse/DEVHUB-1573)]
Upgrade Flora to `v1.3.0` which includes official release of `<ComboBox />` and newly added icons that are needed for Events stuff
> [DEVHUB-1573]: Location and Calendar icon contribution to the systemIcon component

- src/components/card/utils.tsx
- src/hooks/search/utils.ts
- src/utils/format-date.ts
Adding in a couple of quick fixes for some of the issues noted on the events page. Once we have time we should probably come up with a more robust way of transforming API responses so we don't have to make these same checks in multiple parts of the application, but this should work for now.
> Fixes for Timestamps and FIlters on Events page

- src/components/card-section/featured-card-section.tsx
Link to jira ticket [DEVHUB-1545](https://jira.mongodb.org/browse/DEVHUB-1545)
Describe your changes in detail so for example expected behavior, actual behavior, steps to reproduce the behavior
two featured cards visible instead of three
> [DEVHUB-1545] Featured cards modified for tablet dimensions

- src/components/card/card.tsx
- src/components/card/styles.ts
[DEVHUB-1639](https://jira.mongodb.org/browse/DEVHUB-1639)
Use default pill color for all cards.
> [DEVHUB-1639] Use default pill color

- src/components/event-widget/event-widget.test.tsx
- src/components/event-widget/event-widget.tsx
- src/page-templates/content-page/content-page-template.tsx
- src/utils/format-date.ts
[DEVHUB-1650](https://jira.mongodb.org/browse/DEVHUB-1650)
[DEVHUB-1651](https://jira.mongodb.org/browse/DEVHUB-1651)
Fixes date and time formatting and wrong CTA at bottom of Industry Events detail page
> [DEVHUB-1650] & [DEVHUB-1651]: Industry Event Details Page Fixes

- src/components/card-section/featured-card-section.tsx
- src/page-templates/content-type-page/utils.ts
- src/utils/format-date.ts
[DEVHUB-1655](https://jira.mongodb.org/browse/DEVHUB-1655)
These don't have a UAT entry but I noticed them in staging
- Fixes some card styling issues, see screenshots
- Removes "Request an Event" CTA on the Events page. Nothing about this in UAT but I noticed this isn't there in the designs
Before:
After:
> [DEVHUB-1655] Card Styling Fixes for Events

- src/components/article-body/body-components/table-row.tsx
- src/components/article-body/body-components/table.tsx
[DEVHUB-1656](https://jira.mongodb.org/browse/DEVHUB-1656)
> [DEVHUB-1656] Fix table styling

- src/hooks/search/location.ts
- src/utils/format-date.ts
[DEVHUB-1664](https://jira.mongodb.org/browse/DEVHUB-1664)
- Change location search radius from 10 to 100 miles
- Results are now sorted by distance
> [DEVHUB-1664] Change Location Radius to 100 miles, sort results by distance

- src/api-requests/get-industry-events.ts
- src/components/card/utils.tsx
- src/components/search/results.tsx
- src/components/search/types.ts
- src/hooks/search/utils.ts
- src/interfaces/content-item.ts
- src/interfaces/event.ts
- src/service/build-content-items.ts
[(frontend component of) [DEVHUB-1646]](https://jira.mongodb.org/browse/DEVHUB-1646)
- Show city/state/country if available on events cards
- If no image provided, show city in SVG for default event image
> [DEVHUB-1646] Show City/State/Country on Events Cards

- src/components/article-body/body-components/table.tsx
[DEVHUB-1656](https://jira.mongodb.org/browse/DEVHUB-1656)
Align table headers left by default, have table width set to 100%.
> [DEVHUB-1656] Fix table stylings

- playwright-tests/mocks/events.json
- playwright-tests/pages/events.spec.ts
- playwright.config.ts
Forgot to specify a mock name for the events percy test, which was causing the test to timeout once the fallback search results for events was fixed 😕
Also updated the events mock so the percy snapshot is up to date
> Fix Playwright Tests

- src/api-requests/get-industry-events.ts
- src/pages/preview/[...slug].tsx
- src/service/get-preview-content.ts
Adding preview for events (ONlY FOR INDUSTRY EVENTS)
> devcenter events preview

- src/components/card/utils.tsx
[DEVHUB-1683](https://jira.mongodb.org/browse/DEVHUB-1683)
> [DEVHUB-1683] Convert undefined into empty string when location is undefined on event cards.

- next-auth.d.ts
- src/interfaces/UserPreference.ts
- src/interfaces/user-preference.ts
- src/pages/api/auth/[...nextauth].ts
[DEVHUB-1617](https://jira.mongodb.org/browse/DEVHUB-1617) - get user preferences and persist user preferences
> Devhub 1617 get user preferences and persist user preferences in session

- src/components/recommended-section/recommended-content-section.tsx
- src/components/recommended-section/recommended-section.test.tsx
- src/components/recommended-section/recommended-section.tsx
- src/components/recommended-section/recommended-tag-section.tsx
- src/components/recommended-section/styles.ts
- src/hooks/personalization/index.ts
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/personalized-content.ts
- src/pages/index.tsx
[DEVHUB-1612](https://jira.mongodb.org/browse/DEVHUB-1612)
Call recommended content endpoint instead of using mocked data on homepage
> [DEVHUB-1612] Recommended Content API Integration

- src/components/modal/personalization/paginated/personalization-paginated.modal.test.tsx
- src/components/modal/personalization/paginated/personalization-paginated.modal.tsx
- src/components/modal/personalization/scroll/personalization-scroll.modal.tsx
Couple small fixes that were identified during Staging checkouts.
- Fixes icon in Topic Card from being active href's if clicked on when selecting card
- Always scroll to top of Cards container in the Paginated Modal
> [CHORE]: Personalization UI/UX Fixes

- src/pages/api/auth/[...nextauth].ts
- src/pages/api/userPreferences.ts
[DEVHUB-1711](https://jira.mongodb.org/browse/DEVHUB-1711)
Catches a non-200 response when POSTing and GETing the user prefs. This should stop the loop of the onboarding modal.
I also added more detailed logging to debug for [DEVHUB-1710](https://jira.mongodb.org/browse/DEVHUB-1710).
> [DEVHUB-1711] Catch non-200 response, add more information to error logs.

- src/components/modal/personalization/styles.ts
- src/pages/api/auth/[...nextauth].ts
[DEVHUB-1707](https://jira.mongodb.org/browse/DEVHUB-1707), [DEVHUB-1711](https://jira.mongodb.org/browse/DEVHUB-1711)
For [DEVHUB-1707](https://jira.mongodb.org/browse/DEVHUB-1707):
Before:
After:
> [DEVHUB-1707, 1711] Fix token identifier issue, Fix padding issue.

- environments/prod.yaml
- environments/staging.yaml
- src/pages/api/personalized-content.ts
Causing Container creation to fail.
> [FIX] Remove REALM_API_KEY references

- package.json
- src/components/layout.tsx
> [HOTFIX]: Consistent Nav zIndex Overlapping NavBar

- yarn.lock
> manually update yarn lock file

- package.json
- src/components/layout.tsx
- yarn.lock
> Production Hotfix: Consistent Nav Mobile Overlay

- .percy.yml
- package.json
- playwright-tests/pages/languages.spec.ts
- playwright-tests/utils.ts
- src/utils/get-related-content.ts
- yarn.lock
[DEVHUB-1688](https://jira.mongodb.org/browse/DEVHUB-1688) (the major part of the work for this ticket was done [here](https://github.com/mongodb/devcenter/pull/446))
Adding a couple more things to the Percy configuration to try to make it more consistent between runs.
- Added a `.percy.yml` file. Uses the default values for now, but I thought adding it might make future config changes more convenient
- Remove srcset attributes from images which seems to help consistency (the browser swapping between images in the srcset when the width changed was causing some inconsistencies)
- Remove random sorting of related content on content pages when mocking is enabled, readded this section to snapshots
- For some reason we didn't have a Percy test for the languages page, so I added it
I also …
> [rest of DEVHUB-1688] Percy fixes

- src/pages/sitemap/sitemap-index.xml.ts
Link to jira ticket [UP-5883](https://jira.mongodb.org/browse/UP-5883)
Adds /academia page to DevCenter sitemap
> [UP-5883]: SEO for https://www.mongodb.com/academia

- src/hooks/search/index.ts
[## Jira Ticket:
Link to jira ticket [DEVHUB-1111]](https://mongodb.slack.com/archives/C01HNKN55SL/p1678916509387329?thread_ts=1678719278.735289&cid=C01HNKN55SL)
Events' different sorting was not being taken into account in all locations.
> [BUG] Sort events correctly

- config/redirects.json
https://jira.mongodb.org/browse/DEVHUB-1691
> DEVHUB-1961 Adding devhub redirect

- src/pages/languages.tsx
[DEVHUB-1667](https://jira.mongodb.org/browse/DEVHUB-1667)
[DEVHUB-1759](https://jira.mongodb.org/browse/DEVHUB-1759)
> [DEVHUB-1667, DEVHUB-1759] Remove C from featured languages on languages page

- environments/preview.yaml
- environments/prod.yaml
- environments/staging.yaml
- src/pages/api/auth/[...nextauth].ts
- src/pages/api/createFeedback.ts
- src/pages/api/personalized-content.ts
- src/pages/api/requestContent.ts
- src/pages/api/updateFeedback.ts
- src/pages/api/userPreferences.ts
There will be a corresponding backend PR, but this just adds the headers that will be necessary, so I'm doing this one first.
Here is the backend PR: https://github.com/10gen/devcenter-backend/pull/68
> [FIX] Add X-API-KEY header for backend calls

- src/utils/tag-to-topic.tsx
[DEVHUB-1708](https://jira.mongodb.org/browse/DEVHUB-1708)
> [DEVHUB-1708] Add mobile topic to technologies

- src/data/constants.ts
> dummy pr to get a new pod in Kanopy

- src/api-requests/get-all-featured.ts
- src/interfaces/featured.ts
- src/service/get-featured-for-topic.ts
> devhub-1792 Fixing featured content

- environments/staging.yaml
> increasing cpu limit

- .drone.yml
- environments/staging.yaml
- package.json
- src/data/constants.ts
Allotting CPU and Memory resources as suggested by Kanopy team
> Cms migration

- config/redirects.json
[DEVHUB-1537](https://jira.mongodb.org/browse/DEVHUB-1537)
> [DEVHUB-1537] Add SEO redirects

- src/pages/preview/[...slug].tsx
- [DEVHUB-1807](https://jira.mongodb.org/browse/DEVHUB-1807)
- This is to fix the flipped logic in this [previously merged PR](https://github.com/mongodb/devcenter/pull/528)
> [DEVHUB-1807] Expose /preview exclusively on staging

- src/pages/_document.tsx
[DEVHUB-1784](https://jira.mongodb.org/browse/DEVHUB-1784)
> [DEVHUB-1784] Make optimizely snippet load sync.

- next.config.js
[DEVHUB-1807](https://jira.mongodb.org/browse/DEVHUB-1807)
> [DEVHUB-1807] Update NextJS Cache Policy to resolve CDN Stale Response

- package.json
- src/utils/client-factory.ts
- yarn.lock
[DEVHUB-1807](https://jira.mongodb.org/browse/DEVHUB-1807)
> [DEVHUB-1807] Resolve fetch invariant error by ApolloClient

- mocks/apollo-handlers.ts
- mocks/update-apollo-mocks.ts
- src/config/api-client.ts
- src/utils/client-factory.ts
[DEVHUB-1825](https://jira.mongodb.org/browse/DEVHUB-1825)
- Removed Strapi-related code
- Patch ReferenceError during jest test
> [DEVHUB-1825] Remove Strapi Code and Patch mock-handler ReferenceError

- src/page-templates/content-page/content-page-template.tsx
Added this tag based on the LinkedIn post inspector's advice, but there is no documentation anywhere on "Published Date", and no solutions I found worked.
> Add author tag for SEO

- src/page-templates/content-page/content-page-template-test-data.json
- src/page-templates/content-page/content-page-template.test.tsx
- src/page-templates/content-page/content-page-template.tsx
- Refactor SEO out and add tests for it
> Refactor and add tests for SEO

- .drone.yml
- environments/prod.yaml
Adding two new keys test test chron jobs pick new values
> Adding new variables for NPM auth for prod cron jobs

- .drone.yml
- environments/prod.yaml
- src/utils/markdown-parser/parse-markdown-to-ast.ts
https://jira.mongodb.org/browse/DEVHUB-1864
> devhub-1864 dummy test to check if tests are passing on production

- .drone.yml
- environments/prod.yaml
> reverting chron job to point to old npm variables

- .drone.yml
> devhub-1846 changing image pull to always

- .npmrc
- .prettierignore
- package.json
- src/components/secondary-nav/desktop.tsx
- src/components/secondary-nav/mobile.tsx
- yarn.lock
[DEVHUB-1868](https://jira.mongodb.org/browse/DEVHUB-1868)
> [DEVHUB-1868] Update mongo nav package

- config/redirects.json
[DEVHUB-1636](https://jira.mongodb.org/browse/DEVHUB-1636)
I have not yet changed the slug in ContentStack. I will change once it is deployed to production. @harikakotipalli @jackyw2018 Are we ok to do a production deploy once this is merged?
> [DEVHUB-1636] Add redirect for data federation article

- src/hooks/search/filter.ts
- src/hooks/search/utils.ts
- This PR addresses the [issue](https://jira.mongodb.org/browse/DEVHUB-1874) that subfilters override the primary filters
> [DEVHUB-1874] Fix Broken Sub-Filter

- src/hooks/search/filter.ts
- src/hooks/search/utils.test.tsx
- Fix the jest-test failure to be compatible with the changes
- Add one more test for subfilters
> [DEVHUB-1874] Fix and add tests for broken subfilters

- src/hooks/search/filter.ts
- src/hooks/search/utils.test.tsx
- src/hooks/search/utils.ts
- Fixed a failed jest test with the subfilter fix
- Added a jest test to test subfilters
> Release-08/14/2023

- src/components/tertiary-nav/tertiary-nav.tsx
- src/page-templates/topic-page/topic-page-template.tsx
[DEVHUB-1541](https://jira.mongodb.org/browse/DEVHUB-1541)
Had to adjust the Tertiary Nav to accommodate, but the rest of the changes should be pretty straightforward.
> [DEVHUB-1541] Add "All <TOPIC> Content" to tertiary nav, linking to search results

- src/service/build-content-items.ts
Account for content with no image in live previews
> [FIX] Account for content with no image in live previews

- src/service/build-content-items.ts
Just putting in a date for unpublished articles.
> [FIX] Live Preview: Add default date for unpublished preview articles

- src/pages/_app.tsx
> test permission commit

- src/data/secondary-nav.ts
https://jira.mongodb.org/browse/DEVHUB-1890
> adding intermediate to expetise level in secondary nav

- src/components/layout.tsx
- src/pages/books.tsx
[DEVHUB-1904](https://jira.mongodb.org/browse/DEVHUB-1904)
This is a quick MVP, so I will refactor when we expand and improve upon this.
> [DEVHUB-1904] Add books page

- src/pages/books.tsx
[DEVHUB-1904](https://jira.mongodb.org/browse/DEVHUB-1904)
> [DEVHUB-1904] MongoDB Press - Update some copy, fix title margins

- src/pages/books.tsx
[DEVHUB-1904](https://jira.mongodb.org/browse/DEVHUB-1904)
> [DEVHUB-1904] Add updated copy/design to MongoDB Press page.

- src/pages/books.tsx
- src/utils/product-to-logo.ts
Adding icon for Atlas stream processing.
> Release 09/26/2023

- config/redirects.json
https://mongodb.slack.com/archives/C01HNKN55SL/p1696018666366879
> [HOTFIX] Add redirect

- sentry.properties
This merge will only take place after @ajhenri leaves a comment in this PR to signal the Sentry transfer.
> Update sentry org for migration purposes

- sentry.properties
Get the updated sentry org into prod
> Deploy 2023-10-03 II

- README.md
- package.json
- yarn.lock
[INFOSEC-32661](https://jira.mongodb.org/browse/INFOSEC-32661)
Update sharp package to 0.32.6
> [INFOSEC-32661] Update Package per Snyk alert

- src/api-requests/get-authors.ts
- src/service/get-all-authors.ts
- [Fix the image destructure issue in Sentry](https://jira.mongodb.org/browse/DEVHUB-1923)
- This PR addresses the incomplete handling in the previous [PR](https://github.com/mongodb/devcenter/pull/622)
> [DEVHUB-1923] fix(sentry-issues): Fix author undefined issued

- src/data/homepage.ts
https://mongodb.slack.com/archives/C01HNKN55SL/p1698255219684009
> Adding code examples for java

- package.json
- src/pages/api/createFeedback.ts
- src/tests/api/createFeedback.test.ts
- yarn.lock
[DEVHUB-1942](https://jira.mongodb.org/browse/DEVHUB-1942)
- Add [Zod](https://zod.dev/) to perform schema validation on incoming body
- Add tests on `feedbackHandler` (i.e., `POST /api/createFeedback`)
> [DEVHUB-1942] Add schema validations and tests to /api/createFeedback

- src/page-templates/content-page/content-page-template.tsx
[DEVHUB-1873](https://jira.mongodb.org/browse/DEVHUB-1873)
> [DEVHUB-1873] Hide ratings and header images for pathfactory.
